server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ems
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect:
        hibernate: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        properties: 
          format-sql: true